[deps]
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
ClimaOcean = "0376089a-ecfe-4b0e-a64f-9c555d74d754"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
NCDatasets = "85f8d34a-cbdd-5861-8df4-14fed0d494ab"
Oceananigans = "9e8cae18-63c1-5223-a75c-80ca9d6e9a09"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[sources]
ClimaOcean = {path = "../../ClimaOcean.jl"}
